// Assets.js
export const ASSETS = {
    Square:   "AgACAgIAAxkBAAJ1ZWm0jZA1LtpDxWffJ1Bqg1Kc71P1AAKwGGsbbd2gSYziRFdNgw-7AQADAgADeQADOgQ",
    // Optional GIF/animation for main square (Telegram animation file_id).
    // If set, only Square will be rendered as animation instead of photo.
    SquareAnimation: "",
    Upgrades: "AgACAgIAAxkBAAIIDGjwMdJjJ2Og78oSdb9MsCFaxXCkAAL6AAEyGx5mgUv6kKUmZlhInwEAAwIAA3gAAzYE",
    Work:     "AgACAgIAAxkBAAIbgmj21GcZZcgUS43IzsiIY7lUZlw5AAJO_TEb8mK4S_3djUxBAAFoQgEAAwIAA3kAAzYE",
    Study:    "AgACAgIAAxkBAAIIMmjwPPTRdlMbg94FLrINNY80phWeAAIEATIbHmaBSzcpvAMR60LjAQADAgADeAADNgQ",
    Home:     "AgACAgIAAxkBAAIINGjwPTCHFhZfpyd57O6Cy0IgEcgxAAIFATIbHmaBS1-IlTwB0GZwAQADAgADeAADNgQ",
    Shop:     "AgACAgIAAxkBAAIINmjwPZk6XsTrnnL1U3jUW_5NBTCIAAIGATIbHmaBS7_72StYRj1CAQADAgADeAADNgQ",
    Casino:   "AgACAgIAAxkBAAIIKmjwO6Iaw-3u90idpLNwbh9CH7ZvAAL-AAEyGx5mgUv9Rg7N8m6HIAEAAwIAA3gAAzYE",
    Gym:      "AgACAgIAAxkBAAIIMGjwPMlt9HSdh92HNuNWi49p7SlPAAIDATIbHmaBS59PjnCeX5ziAQADAgADeAADNgQ",
    Bar:      "AgACAgIAAxkBAAJ2i2m0wIuJA3tzjpA3F7lOJwHc3UD-AALcGGsbbd2gSZTb-TNzlWvDAQADAgADeQADOgQ",
    Farm:     "AgACAgIAAxkBAAKVM2m_47_fS4Lqg8z_CyZ71PRMi2jgAAJxE2sbjgkAAUpfMc7J4n6yEwEAAwIAA3kAAzoE",
    FarmHelp: "AgACAgIAAxkBAAKVMWm_4zgfLLICvfQ7vjxaHk4o-4UsAAMWaxtJbwABSgFDL7NS3bdAAQADAgADeQADOgQ",
    BusinessSupply: "AgACAgIAAxkBAAEBQ4pp8o0T2UFxm368BtI86syzAbRoYgACqBJrG4KzmEvfvE4DWo7m9AEAAwIAA3kAAzsE",
    Syndicate: "AgACAgIAAxkBAAEBAtVp5OdFRwIF7eZlq7dyd1SAlUUqOgACAxRrGxI3KUu7vB_SzxTkJQEAAwIAA3kAAzsE",
    Fishing:   "AgACAgIAAxkBAAEBFPdp6VoXzRhwK1MtX4xo-3xUk3USzgACbRJrG2V-UUuN-xydMNzJ5AEAAwIAA3kAAzsE",
    Stocks:   "AgACAgIAAxkBAAJn9WmrbXiK8hi-yiwr9In39JxC3sslAAIeEWsbkjRgSQ4w2qZRPIfUAQADAgADeQADOgQ",
    Labour:   "AgACAgIAAxkBAAJv0Wmx84cvJbDFdE8U0CEPrNA1jR92AAIUF2sbvFGRSZlhzh63I18xAQADAgADeQADOgQ",
    Thief:    "AgACAgIAAxkBAAJvsWmx787IddMut9amHJiylnQ8EyuNAAINF2sbvFGRSdAHhMeMfhYUAQADAgADeQADOgQ",
    Colosseum: "AgACAgIAAxkBAAK3vmnJybmeAAFNV2MRswhkt1xkueOznAACyhFrG1IHUUqTGFfBKTLxqwEAAwIAA3kAAzoE",
    ColosseumBattle: "AgACAgIAAxkBAAK3Z2nJv57UYylAV5pMtiihBkOuSfJuAAJ3EmsbbuRQSlwUMGXl3uhJAQADAgADeQADOgQ",
    ColosseumWin: "AgACAgIAAxkBAAK4PGnJz5d2BHE_x1TJPismhOmYcXiIAAIHGGsbOq5ISjxGNZO9MuNuAQADAgADeQADOgQ",
    ColosseumLose: "AgACAgIAAxkBAAK4P2nJz842MW4XfnI8lpAt08BANp8TAAIIGGsbOq5ISv8q_evVTcyOAQADAgADeQADOgQ",
    WorkDefault: "AgACAgIAAxkBAAIILmjwPFEJ23xFl1VbwDYaboJgr-c-AAICATIbHmaBS_IBoc4_-Pf1AQADAgADeAADNgQ",
    StudyActive: "AgACAgIAAxkBAAIZomj2Y0q0YtA6HU-1Qf_cLrZ2sqVzAAIQ-jEb8mK4S8FsRMWWAxKPAQADAgADeQADNgQ", 
    GymActive: "AgACAgIAAxkBAAIZvmj2ZHwyVbrhN23DxKWd1TJp8-_LAAIc-jEb8mK4S1f5DWLdS5CuAQADAgADeQADNgQ",
    CityBoard: "AgACAgIAAxkBAAIciGj3ejh_tt_RdC_H9QABv5CS41yIBAACY_8xG_JiwEs7v8wyU9aNlgEAAwIAA3kAAzYE",
    Clan: "AgACAgIAAxkBAAJm8WmrSDU-c29IatDWhusIhHPyab96AAL2FGsbxVtYSaVJZI5Y8aUnAQADAgADeQADOgQ",
    Premium: "AgACAgIAAxkBAAIdiGj36oNXbt67bnkdEmllXUlFOWATAALOBTIbyKTBSwlYKSgTqMsaAQADAgADeQADNgQ", 
    BusinessShawarma: "AgACAgIAAxkBAAIeN2j4KNwhPuT_wKCXPnk1azeE4AG2AALsBjIbyKTBS08rjhx33rE9AQADAgADeQADNgQ",
    BusinessStomatology: "AgACAgIAAxkBAAIgEGj5cG5a2kxu-LhOVOHB6DEIYMnEAAIqAjIbyKTJS9Xq0xq136GaAQADAgADeQADNgQ",
    Business: "AgACAgIAAxkBAAIeN2j4KNwhPuT_wKCXPnk1azeE4AG2AALsBjIbyKTBS08rjhx33rE9AQADAgADeQADNgQ", // ← баннер экрана «Купить бизнес»






  };
  export const JOB_ASSETS = {
    flyers:     "AgACAgIAAxkBAAIX_2j17kRiUTaPYEsbA_lFIKMZti7LAAK8_TEb_p6wS8riGCAnSMlAAQADAgADeQADNgQ",
    dishwasher: "AgACAgIAAxkBAAIX-Wj17jd1OQvAf_sJQk2twxVSfQKmAAK5_TEb_p6wS_Wnsf4JWjwqAQADAgADeQADNgQ",
    waiter:     "AgACAgIAAxkBAAJn32mrZWs4igy1U89Vng6BUb7IFD2qAAIQEWsbkjRgSUAIgQABaQQOZwEAAwIAA3kAAzoE",
    courier:    "AgACAgIAAxkBAAIYAWj17kgAAdu_e3FZlJS1L49IlPQ0tAACvf0xG_6esEs37zMizlnhygEAAwIAA3kAAzYE",
    loader:     "AgACAgIAAxkBAAIX-2j17jsC58ArbDo3GCiVMPxRSjllAAK6_TEb_p6wS76hKG5qDHNDAQADAgADeQADNgQ",
    shawarma_seller: "AgACAgIAAxkBAAIeN2j4KNwhPuT_wKCXPnk1azeE4AG2AALsBjIbyKTBS08rjhx33rE9AQADAgADeQADNgQ",
    dentist: "AgACAgIAAxkBAAIgEGj5cG5a2kxu-LhOVOHB6DEIYMnEAAIqAjIbyKTJS9Xq0xq136GaAQADAgADeQADNgQ",
    qa_engineer: "AgACAgIAAxkBAAJnvWmrTHM0lOr61SC_1lqyd3kGVf9qAAINHmsbkjRYSS8QMvAKIcXqAQADAgADeQADOgQ",
    farmer:      "AgACAgIAAyEFAASvlIMJAAM4aeEdRKXcPkCWf3PY5fUoJuiZyegAAgQTaxsF8whLF3IEL4o3_sgBAAMCAAN5AAM7BA"


  };
 
