// Assets.js
export const ASSETS = {
    Square:   "AgACAgIAAxkBAAIICmjwMblVC7b2MUqyDi6MLzhuz0G2AAL5AAEyGx5mgUtNeIhhSRR7rgEAAwIAA3gAAzYE",
    Upgrades: "AgACAgIAAxkBAAIIDGjwMdJjJ2Og78oSdb9MsCFaxXCkAAL6AAEyGx5mgUv6kKUmZlhInwEAAwIAA3gAAzYE",
    Work:     "AgACAgIAAxkBAAIbgmj21GcZZcgUS43IzsiIY7lUZlw5AAJO_TEb8mK4S_3djUxBAAFoQgEAAwIAA3kAAzYE",
    Study:    "AgACAgIAAxkBAAIIMmjwPPTRdlMbg94FLrINNY80phWeAAIEATIbHmaBSzcpvAMR60LjAQADAgADeAADNgQ",
    Home:     "AgACAgIAAxkBAAIINGjwPTCHFhZfpyd57O6Cy0IgEcgxAAIFATIbHmaBS1-IlTwB0GZwAQADAgADeAADNgQ",
    Shop:     "AgACAgIAAxkBAAIINmjwPZk6XsTrnnL1U3jUW_5NBTCIAAIGATIbHmaBS7_72StYRj1CAQADAgADeAADNgQ",
    Casino:   "AgACAgIAAxkBAAIIKmjwO6Iaw-3u90idpLNwbh9CH7ZvAAL-AAEyGx5mgUv9Rg7N8m6HIAEAAwIAA3gAAzYE",
    Gym:      "AgACAgIAAxkBAAIIMGjwPMlt9HSdh92HNuNWi49p7SlPAAIDATIbHmaBS59PjnCeX5ziAQADAgADeAADNgQ",
    Bar:      "AgACAgIAAxkBAAISG2j0Th-5LINqx2u1BTiG0y1eO0WCAAI1-TEbZOKgS7vdZfukpE2UAQADAgADeQADNgQ",
    WorkDefault: "AgACAgIAAxkBAAIILmjwPFEJ23xFl1VbwDYaboJgr-c-AAICATIbHmaBS_IBoc4_-Pf1AQADAgADeAADNgQ",
    StudyActive: "AgACAgIAAxkBAAIZomj2Y0q0YtA6HU-1Qf_cLrZ2sqVzAAIQ-jEb8mK4S8FsRMWWAxKPAQADAgADeQADNgQ", 
    GymActive: "AgACAgIAAxkBAAIZvmj2ZHwyVbrhN23DxKWd1TJp8-_LAAIc-jEb8mK4S1f5DWLdS5CuAQADAgADeQADNgQ",
    CityBoard: "AgACAgIAAxkBAAIciGj3ejh_tt_RdC_H9QABv5CS41yIBAACY_8xG_JiwEs7v8wyU9aNlgEAAwIAA3kAAzYE",
    Premium: "AgACAgIAAxkBAAIdiGj36oNXbt67bnkdEmllXUlFOWATAALOBTIbyKTBSwlYKSgTqMsaAQADAgADeQADNgQ", 
    Business: "AgACAgIAAxkBAAIeN2j4KNwhPuT_wKCXPnk1azeE4AG2AALsBjIbyKTBS08rjhx33rE9AQADAgADeQADNgQ", // ← баннер экрана «Купить бизнес»






  };
  export const JOB_ASSETS = {
    flyers:     "AgACAgIAAxkBAAIX_2j17kRiUTaPYEsbA_lFIKMZti7LAAK8_TEb_p6wS8riGCAnSMlAAQADAgADeQADNgQ",
    dishwasher: "AgACAgIAAxkBAAIX-Wj17jd1OQvAf_sJQk2twxVSfQKmAAK5_TEb_p6wS_Wnsf4JWjwqAQADAgADeQADNgQ",
    waiter:     "AgACAgIAAxkBAAIX_Wj17kD8GwvXyW-6aI8s2PLSt96hAAK7_TEb_p6wS4mNfmviyyXmAQADAgADeQADNgQ",
    courier:    "AgACAgIAAxkBAAIYAWj17kgAAdu_e3FZlJS1L49IlPQ0tAACvf0xG_6esEs37zMizlnhygEAAwIAA3kAAzYE",
    loader:     "AgACAgIAAxkBAAIX-2j17jsC58ArbDo3GCiVMPxRSjllAAK6_TEb_p6wS76hKG5qDHNDAQADAgADeQADNgQ",
    shawarma_seller: "AgACAgIAAxkBAAIeN2j4KNwhPuT_wKCXPnk1azeE4AG2AALsBjIbyKTBS08rjhx33rE9AQADAgADeQADNgQ",
    dentist: "AgACAgIAAxkBAAIgEGj5cG5a2kxu-LhOVOHB6DEIYMnEAAIqAjIbyKTJS9Xq0xq136GaAQADAgADeQADNgQ"


  };
 